### ISSUE TITLE
Calendar quarter handling not implemented

### ISSUE THREAD

**Issue by PatrickGaissert** [apple/swift-foundation#112]
I find it highly irritating, that even though the "quarter" date component is public and available, it is not implemented in Calendar. I think this is really not a good developer experience, either it should be implemented or removed from all date component APIs.

**Comment by iCharlesHu** [comment]
Hi @PatrickGaissert ! Just to be clear -- we are not planning on removing these components. We simply just haven't gotten to it yet. This project is still under active development and not yet ready for production adoption.

**Comment by PatrickGaissert** [comment]
That's good news, it's just that the quarter components has never been implemented in the old foundation framework and it is currently not marked with TODO in the code. I would be very happy if it was implemented in the future so thank you for the update!
