### ISSUE TITLE
Swift 5.8 regression: `Bundle` is no longer `Sendable`

### ISSUE THREAD

**Issue by NachoSoto** [apple/swift-foundation#136]
**Description**

`Bundle` was `Sendable` in Swift 5.7.x. Starting with Xcode 14.3 beta 1 and Swift 5.8 I see that that extension has been marked `unavailable`:
```swift
@available(*, unavailable)
extension Bundle : @unchecked Sendable {}
```

Was that intended?

**Environment**
- Swift: `swift-driver version: 1.75.1 Apple Swift version 5.8 (swiftlang-5.8.0.117.11 clang-1403.0.22.8.60)`
- Xcode: `14.3 (14E5197f)`
- Deployment target: iOS 12.0

**Comment by jmschonfeld** [comment]
As far as I remember, `Bundle` was never annotated as `Sendable` in Foundation during our initial audit so I'm surprised we've seen it as such in Swift 5.7. Nonetheless, as @parkera mentioned it just needed some tweaks to be truly `Sendable` so in the end it should be `Sendable`

**Comment by jmschonfeld** [comment]
I think at this point, `Bundle` should be marked as `Sendable` across all platforms so this issue should be resolved. I'm going to go ahead and mark this one as completed
