### ISSUE TITLE
Compiling on Linux throws error 

### ISSUE THREAD

**Issue by Higher08** [apple/swift-foundation#183]
Hello. I tried to compile my new test project with swift-foundation. But in linker step it throws following errors:
```
#0 265.7 error: link command failed with exit code 1 (use -v to see invocation)
#0 265.7 /usr/bin/ld.gold: error: /usr/lib/swift_static/linux/libicui18nswift.a(decNumber.ao): multiple definition of 'uprv_decNumberClass(decNumber const*, decContext*)'
#0 265.7 /usr/bin/ld.gold: /build/.build/x86_64-unknown-linux-gnu/release/ICUI18N.build/decNumber.cpp.o: previous definition here
#0 265.7 clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

In my project I include swift-foundation using this code
```
#if canImport(FoundationEssentials)
import FoundationEssentials
import FoundationInternationalization
#else
import Foundation
#endif
```

What's wrong and how I can fix it?

**Comment by iCharlesHu** [comment]
Hey @Higher08 ! Could you provide more details about:
- Which Linux version are you using?
- Which Swift version are you using?
- How are you compiling your code? If it's with Swift Package Manager could you share the relevant bits from `Package.swift`?

**Comment by parkera** [comment]
I think our CI shows we are correctly building now. I'm going to close this pending more information.
