### ISSUE TITLE
Data + Base64

### ISSUE THREAD

**Issue by iCharlesHu** [apple/swift-foundation#222]
Sub issue under https://github.com/apple/swift-foundation/issues/220 tracking Data Base64 encode/decode.

**Comment by natikgadzhi** [comment]
Do we already have Base64 in the new swift-foundation? I just worked on a simplified version of Base64 for SwiftNIO in https://github.com/apple/swift-nio/pull/2509, and I would love to help out if you would be open to guiding me and reviewing.
