### ISSUE TITLE
FormatStyles

### ISSUE THREAD

**Issue by iCharlesHu** [apple/swift-foundation#231]
Umbrella issue to track all `FormatStyle` and `ParseStrategy`s.

**Comment by iCharlesHu** [comment]
https://github.com/apple/swift-foundation/pull/23 did the majority of the work. We'll track the rest format styles separately.

**Comment by itingliu** [comment]
The remaining are tracked in [#239](https://github.com/apple/swift-foundation/issues/239)
These are blocked by having the `FormatInput` types available in the package.
