### ISSUE TITLE
Build Failure "value of type 'Date' has no member 'isValidForEnumeration'"

### ISSUE THREAD

**Issue by theolampert** [apple/swift-foundation#264]
Current main fails to build with the following:

`error: value of type 'Date' has no member 'isValidForEnumeration'` which appears to be an issue introduced here: https://github.com/apple/swift-foundation/pull/260/files#diff-2fcbb38174eacc940468d36fc235cd2461b5f8d6ad113dbafbfcb4bb2f59f83cR370

**Comment by itingliu** [comment]
Thanks. This is resolved at https://github.com/apple/swift-foundation/commit/01dca320515fd2b5dfdd6ebd064d7437e2dd551e
