### ISSUE TITLE
Is the new JSONDecoder still under development? Confused by the readme

### ISSUE THREAD

**Issue by nickbryanmiller** [apple/swift-foundation#332]
I was reading the readme and these lines stood out.

> Building the Foundation package requires the under-development [Swift 5.9 toolchain](https://www.swift.org/download/#swift-59-development) on or later than September 1st, 2023 (46a3b41), on macOS and Linux.

Swift 5.9 has since been released and to my knowledge is shipped with Xcode 15 and iOS 16. Is this JSONDecoder included or is there something else that I need to do to get this improved JSONDecoder in my iOS project (minimum target iOS 16 and Xcode 15)?

I think my answer is that it is included because I also saw these lines.

> The Swift code in the package is the core of the Foundation framework that ships on macOS, iOS, and other Apple platforms. As new Swift implementations of Foundation API are implemented in the package, Apple will use those implementations in the framework as well.

I am just not clear if the plan is for this package to be used vs if it is already used.

Maybe I am the only one confused by the readme but clarification would help! Thank you

**Comment by iCharlesHu** [comment]
> Is this JSONDecoder included or is there something else that I need to do to get this improved JSONDecoder in my iOS project (minimum target iOS 16 and Xcode 15)?

Hi @nickbryanmiller! The new `JSONDecoder` is included in `macOS 14`, `iOS 17`, `watchOS 10`,  and `tvOS 17`. Any iOS apps running on iOS 17 and above will get the new implementation by default, there's no changes on your side needed. 😊
