### ISSUE TITLE
Predicate with range expression can't be encoded

### ISSUE THREAD

**Issue by axelandersson** [apple/swift-foundation#344]
If I create a predicate like this:

```
#Predicate<Dummy> {
    (0...10).contains($0.value)
}
```

And try to encode it with a `JSONEncoder`, I get this error:

`The 'Foundation.PredicateExpressions.RangeExpressionContains<Foundation.PredicateExpressions.ClosedRange<Foundation.PredicateExpressions.Value<Swift.Int>, Foundation.PredicateExpressions.Value<Swift.Int>>, Foundation.PredicateExpressions.KeyPath<Foundation.PredicateExpressions.Variable<PredicateRangeCoding.Dummy>, Swift.Int>>' type is not in the provided allowlist (required by /)`

Even though I've provided a codable configuration:

```
struct Dummy: PredicateCodableKeyPathProviding {
    static var predicateCodableKeyPaths: [String: PartialKeyPath<Dummy>] {
        ["value": \.value]
    }

    let value: Int
}

var configuration = PredicateCodableConfiguration.standardConfiguration
configuration.allowKeyPathsForPropertiesProvided(by: Dummy.self)
```

Encoding succeeds if I explicitly allow this type, like so:

```
configuration.allowType(PredicateExpressions.RangeExpressionContains<PredicateExpressions.ClosedRange<
                        PredicateExpressions.Value<Int>, PredicateExpressions.Value<Int>>,
                        PredicateExpressions.KeyPath<PredicateExpressions.Variable<Dummy>, Int>>.self)
```

More strangely, encoding also succeeds if I first encode a different predicate that does not contain a range, like this one:

```
#Predicate<Dummy> {
    $0.value > 0
}
```

Other types of predicates can be encoded without issue, so it seems specific to the range expression.

I've created a sample project here: https://github.com/ordo-one/external-reproducers/tree/main/swift/predicate-range-coding. I had a issue when building this on the command line, but it worked when building in Xcode, not sure why:

`main.swift:30:24: error: external macro implementation type 'FoundationMacros.PredicateMacro' could not be found for macro 'Predicate'`

Using Xcode 15.0 (15A240d) with Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1).

**Comment by jmschonfeld** [comment]
I posted the linked PR to resolve the root issue here. The related issue you encountered with the unrelated predicate causing this to work seems to be a bug in the compiler to me. I reduced it down to the following code:

```swift
import Foundation

let workingPredicate = #Predicate<Int> {
    $0 > 0
}

let failingPredicate = #Predicate<Int> {
    (0...10).contains($0)
}

print(type(of: workingPredicate.expression))
print(type(of: failingPredicate.expression))
```

This prints out 

```
Comparison<Variable<Int>, Value<Int>>
Comparison<Variable<Int>, Value<Int>>
```

Which is incorrect as `failingPredicate` should print

```
RangeExpressionContains<ClosedRange<Value<Int>, Value<Int>>, Variable<Int>>
```

(which is what get's printed out when I comment out the `workingPredicate`. So in your example, it's not that encoding/decoding `workingPredicate` caused encoding/decoding `failingPredicate` to succeed - it actually appears to be that _defining_ `workingPredicate` causes it to somehow overwrite the definition of `failingPredicate`. Could you file an issue on the main swift repo about this? (cc @DougGregor)

**Comment by axelandersson** [comment]
Thanks @jmschonfeld. I created https://github.com/apple/swift/issues/70365 to track the type issue.
