### ISSUE TITLE
Is Readme instruction up to date?

### ISSUE THREAD

**Issue by GUserx** [apple/swift-foundation#360]
Hello,
Thanks for making Swift Foundation open source!

I am trying to follow the instruction in Readme to add Swift Foundation into my project.

I have:

- Xcode Version 15.1 (15C65)
- Toolchain swift-5.9-DEVELOPMENT-SNAPSHOT-2023-12-06-a
- macOS Sonoma 14.0

My first question about this line in Readme:
**Open Package.swift and select Debug > Test**
I can't find such action in Xcode **Debug > Test**. What I am missing? 🤔

The second question, I tried to build and test the package via `swift test`command in the package directory. Tests pass successfully, but when I am trying to build my project I keep getting errors such as in the screenshot bellow.
<img width="1552" alt="Screenshot 2023-12-23 at 21 30 28" src="https://github.com/apple/swift-foundation/assets/13054591/03b515e8-cb54-4da3-be49-b067f66a4347">

What can possibly go wrong here?

I would greatly appreciate your help!

**Comment by iCharlesHu** [comment]
> What can possibly go wrong here?

Unfortunately this is an actual bug that we are tracking down. Please use the command line at this time.
