### ISSUE TITLE
Improve error handling on localised strings

### ISSUE THREAD

**Issue by admirsaheta** [apple/swift-foundation#428]
Currently, the evaluate functions in both ```StringLocalizedStandardContains``` and ```StringLocalizedCompare``` simply propagate errors thrown by the evaluate functions of their constituent expressions (root and other).  
ref. [here](https://github.com/apple/swift-foundation/blob/main/Sources/FoundationInternationalization/Predicate/LocalizedString.swift)
It might be beneficial to provide more context-specific error messages or handle specific error cases differently.

For example, instead of just propagating errors as is:
```swift
public func evaluate(_ bindings: PredicateBindings) throws -> Output {
    try root.evaluate(bindings).localizedStandardContains(try other.evaluate(bindings))
}
```

What could be done is create a custom error type enum e.g .

```swift
enum PredicateEvaluationError: Error {
    case evaluationFailed(reason: String)
    case invalidInput
    // more case-specific errors
}
```
And then handle errors as follows
```swift
public func evaluate(_ bindings: PredicateBindings) throws -> Output {
    do {
        return try root.evaluate(bindings).localizedStandardContains(try other.evaluate(bindings))
    } catch let error {
        // provide more context-specific error messages.
        throw PredicateEvaluationError.evaluationFailed(reason: "Evaluation failed: \(error.localizedDescription)")
    }
}
```

**Comment by admirsaheta** [comment]
Hey, an example would be:
```swift 
public func evaluateSearchPredicate(_ query: String) throws -> [Product] {
    do {
        // Evaluate predicate to filter products
        let predicate = createPredicate(for: query)
        return try products.filter { try predicate.evaluate($0) }
    } catch let error {
        // Provide more context-specific error messages
        switch error {
            case PredicateEvaluationError.evaluationFailed(let reason):
                throw PredicateEvaluationError.evaluationFailed(reason: "Search failed: \(reason)")
            case PredicateEvaluationError.invalidInput:
                throw PredicateEvaluationError.invalidInput
            default:
                throw PredicateEvaluationError.evaluationFailed(reason: "Search failed due to an unknown error")
        }
    }
}

func createPredicate(for query: String) -> Predicate {
    // Example: name localized standard contains query
    return Predicate(nameLocalizedStandardContains: query)
}
```

Without custom error handling and context-specific messages, if an error occurs during predicate evaluation, the code might simply display a generic error message like "Search failed"

**Comment by jmschonfeld** [comment]
I believe what you're hoping to accomplish is already possible today. The following code works currently:

```swift
do {
    try predicate.evaluate(someInput)
} catch PredicateError.forceCastFailure {
    print("A force cast failed")
} catch PredicateError.forceUnwrapFailure {
    print("A force unwrap failed")
} catch PredicateError.invalidInput {
    print("An operator received an invalid input argument")
} catch PredicateError.undefinedVariable {
    print("Encountered an undefined variable")
}
```

I'm not sure I'm totally following since in your example you both catch a `PredicateEvaluationError` and throw mostly the same `PredicateEvaluationError`. If you wanted, you could instead `throw` any other error type you'd like from `evaluateSearchPredicate` to include more information like the "Search failed:" string. Is there any information from `Predicate` itself that you feel you're missing in the thrown errors? The cases where an error during evaluation can be thrown are pretty minimal so there's not a lot of detail to share beyond what is already exposed via `PredicateError`
