### ISSUE TITLE
Add CNPostalAddressFormatter to FormatStyle

### ISSUE THREAD

**Issue by alpennec** [apple/swift-foundation#575]
A lot of formatters now have an equivalent FormatStyle: https://developer.apple.com/documentation/foundation/formatstyle
But there is no build-in FormatStyle for CNPostalAddressFormatter https://developer.apple.com/documentation/contacts/cnpostaladdressformatter.

Would this make sense to add such a FormatStyle to easily handle international formatting of postal addresses and create strings?

Thanks

**Comment by itingliu** [comment]
`CNPostalAddressFormatter` is owned by the Contacts framework; I think they should continue to vend `FormatStyle` variant if we are to add one. I passed this comment to them, but you're welcome to file feedback on [the bug reporting site](https://developer.apple.com/bug-reporting/) if you want to follow along. Thanks for the report though!

**Comment by itingliu** [comment]
I'm going to close this since it's out of our project's scope :)

**Comment by itingliu** [comment]
I'm going to close this since it's out of our project's scope :)

**Comment by alpennec** [comment]
Thanks for letting me know. I did not know this was for the Contacts framework team. I'll file a feedback.
