### ISSUE TITLE
Un-deprecate contiguous ASCII

### ISSUE THREAD

**Issue by parkera** [apple/swift-foundation#74]
The swift stdlib [deprecated](https://github.com/apple/swift/blob/060d81f6537e5949493d2f28c4506de754f0d2b4/stdlib/public/core/StringGuts.swift#L403) `_isContiguousASCII`, but Foundation depends on it for `String` extensions.

Is there a better entry point to use, or should we remove the deprecation from stdlib?

```
/swift-foundation/Sources/FoundationEssentials/String/String+Essentials.swift:109:70: warning: '_isContiguousASCII' is deprecated
            if encoding == .utf8 || (encoding == .ascii && str._guts._isContiguousASCII) {
```

**Comment by glessard** [comment]
The stdlib should at least have a failable String initializer that can validate ASCII. I _think_ that could replace the current uses we make of the `_isContiguousASCII` property.

**Comment by jmschonfeld** [comment]
This was undeprecated with https://github.com/swiftlang/swift/pull/70726 so I think we can go ahead and resolve this
