### ISSUE TITLE
Put URL downloading back into Data(contentsOf:)

### ISSUE THREAD

**Issue by parkera** [apple/swift-foundation#819]
The new Data reading API doesn't support non-file URLs on non-Darwin systems. This could be a compatibility issue.

see also: https://forums.swift.org/t/data-contentsof-and-new-swift-foundation/73632

**Comment by jmschonfeld** [comment]
https://github.com/apple/swift-foundation/pull/820 and https://github.com/apple/swift-corelibs-foundation/pull/5049 will resolve this by adding an up-call to `FoundationNetworking` on `main`, I'll also cherry-pick this back to `release/6.0` for Swift 6

**Comment by jmschonfeld** [comment]
Fixed on `main`, https://github.com/apple/swift-foundation/pull/826 and https://github.com/apple/swift-corelibs-foundation/pull/5058 are the 6.0 cherry-pick PRs

**Comment by jmschonfeld** [comment]
6.0 PRs are now merged as well - marking this as resolved
