### ISSUE TITLE
Cannot instantiate String with Data with encoding nonLossyASCII

### ISSUE THREAD

**Issue by Frizlab** [apple/swift-foundation#929]
The following code returns `nil` with Swift 6.0 and Swift 6.0-snapshot-2024-09-17 on Linux, but returns the proper String on macOS: `String(data: Data(#"yolo"#.utf8), encoding: .nonLossyASCII)`.
I believe macOS is in the right.

**Comment by jmschonfeld** [comment]
As a workaround for now on Linux, you can use `.ascii` instead of `.nonLossyASCII` - decoding bytes with ASCII is always considered lossy, `nonLossyASCII` only has different effects when converting a string to bytes

**Comment by Frizlab** [comment]
@jmschonfeld I don’t think that’s true:
```swift
print(String(data: Data("yolo\\012".utf8), encoding: .nonLossyASCII))
print(String(data: Data("yolo\\012".utf8), encoding: .ascii))
```
First version prints `yolo\n` the other prints `yolo\\012`.

**Comment by Frizlab** [comment]
@jmschonfeld

```text
macOS 15
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0
```
Also on macOS 14.7 w/ Xcode 15.2.

12 in octal is a newline in ascii.

Interestingly, `"yélo".data(using: .nonLossyASCII)` works on macOS 14 (returns the Data for the literal string `y\351lo`) but on macOS 15 it returns `nil`.
